WARNING    Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54a62441c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/283343636cd28ae19555e9bd6f42d476/execute/sync
WARNING    Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54a623ce20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/283343636cd28ae19555e9bd6f42d476/execute/sync
WARNING    Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54a623cac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/283343636cd28ae19555e9bd6f42d476/execute/sync
